name: migrant_source_fs
version: 0.1.1
description: Local file system migrations source for Migrant
homepage: "https://github.com/f3ath/migrant-source-fs"

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  migrant: ^0.3.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.20.1
  coverage: ^1.9.0
  check_coverage: ^0.0.7
  cider: ^0.2.0

cider:
  link_template:
    tag: https://github.com/f3ath/migrant-source-fs/releases/tag/%tag%
    diff: https://github.com/f3ath/migrant-source-fs/compare/%from%...%to%